// <auto-generated />
using System;
using AcreditacionesApp.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AcreditacionesApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AcreditacionesApp.Api.Entities.Acreditacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EntidadAcreditadora")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("entidad_acreditadora");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaEmision")
                        .HasColumnType("date")
                        .HasColumnName("fecha_emision");

                    b.Property<DateOnly>("FechaVencimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<int>("TipoAcreditacionId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_acreditacion_id");

                    b.HasKey("Id")
                        .HasName("pk_acreditacion");

                    b.HasIndex("TipoAcreditacionId")
                        .HasDatabaseName("ix_acreditacion_tipo_acreditacion_id");

                    b.ToTable("acreditacion", (string)null);
                });

            modelBuilder.Entity("AcreditacionesApp.Api.Entities.RequisitoAcreditacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcreditacionId")
                        .HasColumnType("integer")
                        .HasColumnName("acreditacion_id");

                    b.Property<bool>("Cumplido")
                        .HasColumnType("boolean")
                        .HasColumnName("cumplido");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<DateOnly?>("FechaCumplimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_cumplimiento");

                    b.Property<bool>("Obligatorio")
                        .HasColumnType("boolean")
                        .HasColumnName("obligatorio");

                    b.HasKey("Id")
                        .HasName("pk_requisitos_acreditacion");

                    b.HasIndex("AcreditacionId")
                        .HasDatabaseName("ix_requisitos_acreditacion_acreditacion_id");

                    b.ToTable("requisitos_acreditacion", (string)null);
                });

            modelBuilder.Entity("AcreditacionesApp.Api.Entities.TipoAcreditacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int>("VigenciaMeses")
                        .HasColumnType("integer")
                        .HasColumnName("vigencia_meses");

                    b.HasKey("Id")
                        .HasName("pk_tipo_acreditacion");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ix_tipo_acreditacion_nombre");

                    b.ToTable("tipo_acreditacion", (string)null);
                });

            modelBuilder.Entity("AcreditacionesApp.Api.Entities.Acreditacion", b =>
                {
                    b.HasOne("AcreditacionesApp.Api.Entities.TipoAcreditacion", "Tipo")
                        .WithMany()
                        .HasForeignKey("TipoAcreditacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_acreditacion_tipo_acreditacion_tipo_acreditacion_id");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("AcreditacionesApp.Api.Entities.RequisitoAcreditacion", b =>
                {
                    b.HasOne("AcreditacionesApp.Api.Entities.Acreditacion", null)
                        .WithMany("Requisitos")
                        .HasForeignKey("AcreditacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_requisitos_acreditacion_acreditacion_acreditacion_id");
                });

            modelBuilder.Entity("AcreditacionesApp.Api.Entities.Acreditacion", b =>
                {
                    b.Navigation("Requisitos");
                });
#pragma warning restore 612, 618
        }
    }
}
